// Generated by CoffeeScript 1.4.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  module.exports = function(_arg) {
    var config, docpad, newUrl, newpost, oldUrls, server;
    server = _arg.server, docpad = _arg.docpad, newpost = _arg.newpost;
    config = docpad.getConfig();
    oldUrls = config.templateData.site.oldUrls || [];
    newUrl = config.templateData.site.url;
    server.use(function(req, res, next) {
      var _ref;
      if (_ref = req.headers.host, __indexOf.call(oldUrls, _ref) >= 0) {
        return res.redirect(newUrl + req.url, 301);
      } else {
        return next();
      }
    });
    return server.post('/hook/new-post', function(req, res) {
      newpost(req);
      return res.end();
    });
  };

}).call(this);
